### ISSUE TITLE
Problem in the state of lights in bookmarks

### ISSUE THREAD

**Issue by Eric6464** [calaos/calaos-web-app#11]
In the state of lights set in bookmarks, The lights in a same room could be separated.
This arrive when (for exemple) :
I put on the lights of the swimming pull named "lumière plafond".
I put on a light in the "sous sol"
I put on a light (2 in my example) in the swimming pull.... the swimming pull lights are separated.
If i stop to use Calaos mobile and start it again everything is ok.
![mobile](https://cloud.githubusercontent.com/assets/9049130/4783842/fddb0ff6-5d37-11e4-8596-8f3c1815b479.png)

We can see my example in the attached file.

**Comment by raoulh** [comment]
This is a calaos_mobile bug, not calaos-webapp, please re-open a new bug in the calaos_mobile project
