### ISSUE TITLE
Variable display

### ISSUE THREAD

**Issue by steevedu49** [calaos/calaos-web-app#12]
The internal variables "internalstring" displays the variable name in place of the variable value
This bug is also present in the mobile ios app

**Comment by raoulh** [comment]
I don't have this bug, it works for me. Can you explain an example where it failes please?

**Comment by steevedu49** [comment]
For testing I create an internal variable. This text variable is set to "ok" .
This is what it gives in Calaos_WEB and Calaos_IOS
In Calaos_WEB the value is displayed .
In Calaos_IOS value does not appear.
![prop_var](https://cloud.githubusercontent.com/assets/5489198/5604196/e3e04b38-93ac-11e4-9b76-e74178b11122.png)
![img_1236](https://cloud.githubusercontent.com/assets/5489198/5604198/f012b4a4-93ac-11e4-8fea-63c71ed47e68.JPG)
![test_webapp](https://cloud.githubusercontent.com/assets/5489198/5604199/f67a1e90-93ac-11e4-8ba7-dbec31ad1cff.png)

**Comment by raoulh** [comment]
This is a bug in calaos_mobile, not calaos-webapp
